### ISSUE TITLE
New tool: Django

### ISSUE THREAD

**Issue by JuliusWiedemann** [julianYaman/tooldb#2]
## Required Information

* Name: Django
* Short description: Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.
* Long description: With Django, you can take web applications from concept to launch in a matter of hours. Django takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.
* Categories: Python Library, Web Tool
* URL: https://www.djangoproject.com/
* Icon: https://static.djangoproject.com/img/icon-touch.e4872c4da341.png

## Additional information

* Link to GitHub Repo of the tool (not required): https://github.com/django/django
* Link to Twitter of the tool(not required): https://twitter.com/djangoproject
* Images (not required): (can be links to images)

**Comment by julianYaman** [comment]
Added the tool, thank you!
